version: "3.8"

services:
  api:
    container_name: api
    restart: always
    build: .
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    env_file:
      - ./.env
    command: --auth
    volumes:
      - ./mongo.init.js:/docker-entrypoint-initdb.d/mongo.init.js:ro
